/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a ngconnectorif_adaptor.h: ../NGBrowser/ngconnectorif.xml
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef NGCONNECTORIF_ADAPTOR_H
#define NGCONNECTORIF_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface NGConnector.Connection
 */
class ConnectionAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "NGConnector.Connection")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"NGConnector.Connection\">\n"
"    <method name=\"complete\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"str\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ConnectionAdaptor(QObject *parent);
    virtual ~ConnectionAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void complete(const QString &str);
Q_SIGNALS: // SIGNALS
};

#endif
